service: notification-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  lambdaHashingVersion: 20201221
  iam:
   role:
    statements:
     - Effect: Allow
       Action:
          - ses:*
          - sqs:*
       Resource: "*"
     
        


functions:
  sendEmail:
     handler: sendEmail.sendEmail
     reservedConcurrency: 10
     events:
      - http:
         path: email
         method: post
         cors: true
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"
        

